#!/bin/bash

ls /sys/firmware/efi/efivars
timedatectl set-ntp true

fdisk /dev/sda << EOF
g
n


+260M
t
1
n



t
2
23
w
EOF

mkfs.ext4 /dev/sda2
mkfs.fat -F32 /dev/sda1
mkdir /mnt/efi
mount /dev/sda2 /mnt
mount /dev/sda1 /mnt/efi

pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
cp install_sys /mnt
arch-chroot /mnt
rm /mnt/install_sys

reboot