#!/bin/bash
# Jason's Arch Linux Installation Scripts
# Run this script inside the live environment

yes_no_prompt () {
    read -p "[INSTALLER] $1" -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]]
}

p () {
    echo "[INSTALLER] $1"
}

inp () {
    local -n ref=$2
    read -p "[INSTALLER] $1" ref
}

if ! ls /sys/firmware/efi/efivars
then
    p "UEFI mode is not on. Installation cancelled."
    exit
fi

timedatectl set-ntp true

while :
do
    p "Current block devices:"
    fdisk -l
    inp "Enter the correct block device name (e.g. /dev/sda): " blkdev
    if [[ -b $blkdev ]] && yes_no_prompt "Partitioning $blkdev. Continue? (y/n): "
    then
        break
    fi
    p "Choose another block device."
done

# Partition layout
# Mount point   Partition               Partition type              Size
# /mnt/boot     EFI system partition    EFI System (1)              260 MiB
# /mnt          Root partition          Linux root (x86-64) (23)    Remaining

fdisk $blkdev << EOF
g
n


+260M
t
1
n



w
EOF
p "Disks partitioned successfully"

while :
do
    p "Now manually enter the partition device names from the following list:"
    fdisk -l
    inp "Which is the ESP? (e.g. /dev/sda1): " esp
    inp "Which is the root partition? (e.g. /dev/sda2): " root
    if [[ -b $esp ]] && [[ -b $root ]] && yes_no_prompt "The ESP is $esp and the root partition is $root. Correct? (y/n): "
    then
        break
    fi
    p "Enter the correct partition device names."
done

lvm_yes=0
if yes_no_prompt "Set up LVM on LUKS? (y/n)"
then
    lvm_yes=1
    while :
    do
        p "Set a password for the encrypted device."
        if cryptsetup luksFormat $root
        then
            break
        fi
    done
    while :
    do
        p "Enter your password again to open the encrypted device."
        if cryptsetup open $root cryptlvm
        then
            break
        fi
    done
    pvcreate /dev/mapper/cryptlvm
    vgcreate vg1 /dev/mapper/cryptlvm
    lvcreate -l 100%FREE vg1 -n root
    lvresize -L -4G vg1/root            # Subtract 4 GiB for snapshots
    root="/dev/vg1/root"
    p "LVM on LUKS setup complete"
fi

p "Formatting and mounting partitions"
mkfs.ext4 $root
mkfs.fat -F32 $esp
mount $root /mnt
mkdir /mnt/boot
mount $esp /mnt/boot
p "Formatting complete and mounted"

p "Installing Arch Linux base packages"
pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

if ! yes_no_prompt "Installation complete. After chrooting into the new system, run ./install_sys. Continue? (y/n): "
then
    p "Too late ;)"
fi

cp install_sys /mnt
sed -i "s/<LVM_YES_PLACEHOLDER>/$lvm_yes/" /mnt/install_sys
sed -i "s/<ESP_PLACEHOLDER>/${esp//\//\\/}/" /mnt/install_sys
chmod +x /mnt/install_sys

arch-chroot /mnt
rm /mnt/install_sys

p "Type reboot to reboot into Arch Linux!"