#!/bin/bash
# Jason's Arch Linux Installation Scripts
# Run this script once chrooted into the installed system

lvm_yes=LVM_YES_PLACEHOLDER
esp=ESP_PLACEHOLDER

yes_no_prompt () {
    read -p "[INSTALLER] $1" -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]]
}

p () {
    echo "[INSTALLER] $1"
}

inp () {
    local -n ref=$2
    read -p "[INSTALLER] $1" ref
}

ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
hwclock --systohc
p "Time zone configuration complete"

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
p "Localization configuration complete"

hostname="myhostname"
echo $host_name >> /etc/hostname
echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t$hostname" >> /etc/hosts
p "Network configuration complete. You may want to install a network manager."

pacman -S vim

if [[ $lvm_yes == 1 ]]
then
    pacman -S lvm2
    p "Now, configure mkinitcpio. Add the following hooks to the HOOKS array: keyboard, keymap, encrypt, lvm2"
    p "Example: HOOKS=(base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck)"
    inp "Press Enter to continue to vim" x
    vim /etc/mkinitcpio.conf
    mkinitcpio -P
fi

pacman -S grub efibootmgr
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB

if [[ $lvm_yes == 1 ]]
then
    p "Now configure GRUB to work with LVM on LUKS."
    lsblk -f
    inp "Enter the correct device UUID for the encrypted device: " uuid
    p "Now edit GRUB_CMDLINE_LINUX_DEFAULT to include the following parameters:"
    params="cryptdevice=UUID=$uuid:cryptlvm root=/dev/vg1/root"
    p $params
    p "While in vim, type :!cat params to see the params again"
    echo $params >> params
    inp "Press Enter to continue to vim" x
    vim /etc/default/grub
    rm params
fi

pacman -S amd-ucode
grub-mkconfig -o /boot/grub/grub.cfg

p "Set the root password."
passwd

pacman -S xfce4

if yes_no_prompt "Exit to the live environment? (y/n): "
then
    exit
fi