#!/bin/bash

yes_no_prompt () {
    read -p "[INSTALLER] $1" -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]]
}

p () {
    echo "[INSTALLER] $1"
}

inp () {
    local -n ref=$2
    read -p "[INSTALLER] $1" ref
}

file_check () {
    p "Double check the contents of $1:"
    if [[ ! -z $2 ]]
    then
        cat $1 | grep $2
    else
        cat $1
    fi
    yes_no_prompt "Does that look correct? (y/n): "
}

inp "fdsa"