#!/bin/bash

sudo pacman -S xorg-server lightdm lightdm-gtk-greeter bspwm sxhkd alacritty

install -Dm755 /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/bspwmrc
install -Dm644 /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/sxhkdrc

sed -i "s/urxvt/alacritty/" ~/.config/sxhkd/sxhkdrc