#!/bin/bash

# AUR installs:
# polybar

# xsecurelock   - lock screen
# rofi          - run menu
# picom         - compositor
# nitrogen      - wallpaper
# xorg-xsetroot - cursor settings
# lxappearance  - gtk theme
# xorg-xrandr   - xorg stuff
# dunst         - notifications

sudo pacman -S xorg-server bspwm sxhkd alacritty xsecurelock rofi picom nitrogen xorg-xsetroot lxappearance xorg-xrandr dunst #lightdm lightdm-gtk-greeter
