#!/bin/bash

# AUR installs:
# polybar

# xsecurelock   - lock screen
# rofi          - run menu
# picom         - compositor
# nitrogen      - wallpaper
# xorg-xsetroot - cursor settings

sudo pacman -S xorg-server bspwm sxhkd alacritty xsecurelock rofi picom nitrogen xorg-xsetroot #lightdm lightdm-gtk-greeter

sed -i "s/urxvt/alacritty/" ~/.config/sxhkd/sxhkdrc
