#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
nitrogen --restore &
~/.config/polybar/launch.sh
ibus-daemon -drxR
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
#bspc config top_monocle_padding  8

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a polybar layer=ABOVE

xsetroot -cursor_name left_ptr

flag_floating_windows() {
    bspc subscribe node_state | while read -r _ _ _ node state status; do
        if [[ "$state" == "floating" ]]; then
            case "$status" in
                off) xprop -id "$node" -remove _COMPTON_SHADOW;;
                on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
            esac
        fi
    done
}

#flag_floating_windows &
